version: '3.8'
services:

  vault:
    image: hashicorp/vault
    container_name: vault
    restart: on-failure:10
    ports:
      - "8201:8201"
    env_file: .env
    environment:
      - VAULT_ADDR=http://0.0.0.0:8201
    cap_add:
      - IPC_LOCK
    volumes:
      - ../vault:/vault_data
      - vault_data:/data
    healthcheck:
      retries: 5
    command: ./vault_data/workflow-vault.sh
     

  db:
    container_name: foodgram-db
#    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#      - ../vault/db-auth.sh:/db-auth.sh
    env_file: .env
    build: ../postgree/
    depends_on:
      - vault
#    environment:
#      POSTGRES_DB: foodgram_db
#      POSTGRES_USER: foodgram_user
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_password}
    restart: always
    command: /bin/bash -c "/db-auth.sh"
    

  backend:
    container_name: foodgram-backend
    #image: leaderofthebadgers/foodgram-backend:latest
    build: ../backend/
    restart: always
    depends_on:
      - db
      - vault
    env_file: .env
    environment:
    - VAULT_ADDR=http://vault:8201
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - static_value:/app/static/
      - media_value:/app/media/
      - fonts:/app/fonts/


  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
    restart: always



volumes:
  vault_data:
  postgres_data:
  static_value:
  media_value:
  fonts:


